#!/bin/sh
PATH=/bin:/sbin:/usr/bin:/usr/sbin:/usr/local/bin:/usr/local/sbin:/rescue

# shellcheck source=runit/functions
. /usr/local/etc/runit/functions

detect_jail

[ -x /usr/local/etc/runit/local ] && /usr/local/etc/runit/local

/usr/sbin/utx boot

exec env - PATH=$PATH runsvdir -P /var/service 'log: ................................................................................................................................................................................'
